apiVersion: v2
name: moodle-operator
description: "Helm chart for deploying the Moodle Kubernetes Operator and CRDs. Uses the bjw-s/app-template library (alias: operator) to render the controller, ServiceAccount, RBAC, and an HTTP Service with secure defaults. All behavior is configurable via values."
icon: https://moodle.org/theme/image.php/moodleorg/theme/1692005413/moodle_logo_small

type: application
kubeVersion: ">=1.28.0-0"
version: 0.1.1
appVersion: "1.16.0"

keywords:
  - moodle
  - operator
  - kubernetes
  - education
  - helm

maintainers:
  - name: Stephane Segning
    email: selastlambou@gmail.com
  - name: Adorsys GIS
    email: gis-udm@adorsys.com

dependencies:
  - name: app-template
    version: 4.3.0
    repository: https://bjw-s-labs.github.io/helm-charts
    alias: operator
